from LerDados import function_dados
import  pymssql


server = '192.168.252.10'
user = 'zuri.dev'
password = 'P04@sot28+'

df = function_dados()

conn = pymssql.connect(server, user, password, "sbkoficio")
cursor = conn.cursor()
# Insert Dataframe into SQL Server:
for index, row in df.iterrows():
    cursor.execute("INSERT INTO AUX_CAPTURAANTECIPADA ('DENOMINACAO','MUNICIPIO','UF','DOCUMENTO',TAMANHO,AUDIENCIA,TUTELAS,COD_CAUSA,DATA_DE_CADASTRAMENTO,N_PROCESSO,DATA_DE_INICIO_ATENDIMENTO,NUMERAL_DA_VARA,ORGAO_TRIBUNAL,VALOR_PLEITO,TIPO_ACAO,ADVOGADO_PARTE_CONTRA,N_OAB_ADVOGADO_PARTE_CONTRA,PARTE_CONTRA,PARTE_CONTRA_CPF_CNPJ,PARTE_CONTRA_IDENTIDADE,PARTE_PRO,DT_VINCULACAO_DOC,LOCAL_SERVICO,DT_AUDIENCIA,HR_AUDIENCIA,AUDIENCIA_NOVA,CITE_SE,PRIORIDADE_CAUSA_DESCRICAO,STATUS_DO_PROCESSO,MOTIVO_DO_STATUS,DATA_DA_CONFIRMACAO,DT_FATO_GERADOR,DT_REGISTRO,STATUS_REGISTRO,ID_DOCUMENTO,ID_IMAGEM,DATA_GERACAO,FORNECEDOR,COVID_19) values(?,?,?)", row.DENOMINACAO,row.MUNICIPIO,row.UF,row.DOCUMENTO,row.TAMANHO,row.AUDIENCIA,row.TUTELAS,row.COD_CAUSA,row.DATA_DE_CADASTRAMENTO,row.N_PROCESSO,row.DATA_DE_INICIO_ATENDIMENTO,row.NUMERAL_DA_VARA,row.ORGAO_TRIBUNAL,row.VALOR_PLEITO,row.TIPO_ACAO,row.ADVOGADO_PARTE_CONTRA,row.N_OAB_ADVOGADO_PARTE_CONTRA,row.PARTE_CONTRA,row.PARTE_CONTRA_CPF_CNPJ,row.PARTE_CONTRA_IDENTIDADE,row.PARTE_PRO,row.DT_VINCULACAO_DOC,row.LOCAL_SERVICO,row.DT_AUDIENCIA,row.HR_AUDIENCIA,row.AUDIENCIA_NOVA,row.CITE_SE,row.PRIORIDADE_CAUSA_DESCRICAO,row.STATUS_DO_PROCESSO,row.MOTIVO_DO_STATUS,row.DATA_DA_CONFIRMACAO,row.DT_FATO_GERADOR,row.DT_REGISTRO,row.STATUS_REGISTRO,row.ID_DOCUMENTO,row.ID_IMAGEM,row.DATA_GERACAO,row.FORNECEDOR,row.COVID_19)
    conn.commit()
cursor.close()